jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ1
jwt:
  header: Authorization
  tokenHead: 'Bearer '
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: cn.linfenw.domain
pre:
  security:
    social:
      gitee:
        app-id: a030c1e5e6bef403e6d7debbfb6586016ce86090587fdc6ba2e53926c911fcef
        app-secret: 1b61486af774e7066fe6bffe67b6d76d91952b8829f9322ca6d7820439aa65ce
        provider-id: gitee
      github:
        app-id: 0e4b224d9c629ce3f3ea
        app-secret: 31fc9751b005f5e40113fc3f07b5beae0a7dad25
        provider-id: github
      qq:
        app-id: 101852664
        app-secret: 3a3b899e2b89b74724ac164d0e6006b8
        provider-id: qq
      weixin:
        app-id: wx27e0de97cfa87385
        app-secret: 1f8958cc2cb233d7a4f8b7d364bcb72c
        provider-id: weixin
  tenant:
    ignoreTenantTables:
      - sys_tenant
      - sys_menu
      - sys_user_role
      - sys_role_menu
      - sys_role_dept
      - sys_user_role
      - sys_dict_item
      - TABLES
      - COLUMNS
      - sys_job
    tenantIdColumn: tenant_id
  url:
    address: http://localhost:9528
server:
  http2:
    enabled: true
  undertow:
    buffer-size: 2048
    direct-buffers: true
    io-threads: 4
    worker-threads: 20
  servlet:
    context-path: /linfen
  compression:
    enabled: true #开启 gzip 压缩
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 3
    password: P@ssw0rd
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://8.135.65.163:3366/linfen_blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
  mail:
    host: smtp.qq.com
    username: ENC(osJknMmZMlmDylG2aauZRf3ZTEyH6bWN)
    password: ENC(0lmSKzAD+NKDfWtd6zDpG1UpwwdC9la8z5L23wkK57s=)
    default-encoding: UTF-8
    properties:
      mail:
      smtp:
      socketFactory:
        port: 587
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
      auth: true
      starttls:
        enable: true
        required: true
    port: 587
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 1
    host: 8.135.65.163
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30000ms
        min-idle: 1
    password: ''
    port: 6379
    timeout: 6000ms

#  devtools
  devtools:
    restart:
      enabled: true

# 文件上传配置
  servlet:
    multipart:
      max-request-size: 25MB
      max-file-size: 25MB

#debug
debug: true

uploadFileServerPathPrefix: /Users/linfen/Desktop/files

#七牛云配置
qiniu:
  accessKey: ENC(OnwdFZipRMP0nXmz+LBEzdIfof84BPUy3ZFwdAzPmFMFzao2kNyHImRhhVTPXKhYeeBGA1w7Bfk=)
  secretKey: ENC(774EgysllH7G0Cp/PR8Wnh7bMto84dpDXqHbwHC/MAiu8xX2g7euHZgu/h4aBwzJrl75uMsR/kU=)
  bucketName: linfen-blog
  fileDomain: ENC(LxSxhRDbQzUPOX1ux74i6vdFUUhJmovycQ2FYbOEK5pBPp1+b6GFJTNS+Mnm7oER) #文件访问域名前缀

linfen-blog:
  #第三方授权登录
  oauth:
    #回调地址
    callBackBaseUrl: http://www.linfenw.cn:8081/linfen/callback
    #前端地址和端口
    vueBaseUrl: http://www.linfenw.cn
